--1 
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도" FROM TB_STUDENT WHERE DEPARTMENT_NO = '002' ORDER BY ENTRANCE_DATE;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE LENGTH(PROFESSOR_NAME)!= 3;

--3
SELECT PROFESSOR_NAME"교수이름", SYSDATE - TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YY-MM-DD') "나이" FROM TB_PROFESSOR;

SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 4), 'YYYY') FROM TB_PROFESSOR;
SELECT TO_NUMBER(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'YYYY'))FROM TB_PROFESSOR;


SELECT TO_CHAR(SUBSTR(PROFESSOR_SSN, 1, 2), 'YYYY') FROM TB_PROFESSOR;

--주민 -> 날짜형식 -> 숫자형식


select * from tb_class;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;