CREATE TABLE VIDEO(
    VIDEO_CODE NUMBER,
    VIDEO_TITLE VARCHAR2(100),
    VIDEO_DESC VARCHAR2(200),
    VIDEO_DATE DATE,
    VIDEO_VIEWS NUMBER,
    VIDEO_URL VARCHAR2(300),
    VIDEO_PHOTO VARCHAR2(300),
    CATEGORY_CODE NUMBER,
    CHANNEL_CODE NUMBER,
    MEMBER_ID VARCHAR2(200)
);

CREATE TABLE CHANNEL (
    CHANNEL_CODE NUMBER,
    CHANNEL_NAME VARCHAR2(100),
    CHANNEL_DESC VARCHAR2(200),
    CHANNEL_DATE DATE,
    MEMBER_ID VARCHAR2(200)
);

--테이블 이름 유저 안되어서 멤버
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(200),
    MEMBER_PASSWORD VARCHAR2(200),
    MEMBER_NICKNAME VARCHAR2(200),
    MEMBER_EMAIL VARCHAR2(200),
    MEMBER_PHONE VARCHAR2(200),
    MEMBER_GENDER CHAR,
    MEMBER_AUTHORITY VARCHAR2(200)
);

--테이블 이름 라이크 안되어서 비디오라이크
CREATE TABLE VIDEO_LIKE(
    V_LIKE_CODE NUMBER,
    V_LIKE_DATE DATE,
    VIDEO_CODE NUMBER,
    MEMBER_ID VARCHAR2(200)
);

--필기다안됨
CREATE TABLE VIDEO_COMMNET(
    COMMENT_CODE NUMBER,
    COMMENT_DESC VARCHAR2(300),
    COMMENT_DATE DATE,
    VIDEO_CODE NUMBER,
    MEMBER_ID VARCHAR2(200)
);

CREATE TABLE SUBSCRIBE(
    SUBS_CODE NUMBER,
    SUBS_DATE DATE,
    MEMBER_ID VARCHAR2(200),
    CHANNEL_CODE NUMBER
);

CREATE TABLE COMMNET_LIKE(
    COMM_LIKE_CODE NUMBER,
    COMM_LIKE_DATE DATE,
    COMMENT_CODE NUMBER,
    MEMBER_ID VARCHAR2(200)
);

CREATE TABLE CATEGORY(
    CATEGORY_CODE NUMBER,
    CATEGORY_NAME VARCHAR2(50)
    
);

ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORY_CODE_PK PRIMARY KEY(CATEGORY_CODE);
ALTER TABLE CHANNEL ADD CONSTRAINT CHANNEL_CODE_PK PRIMARY KEY(CHANNEL_CODE);
ALTER TABLE COMMENT_LIKE ADD CONSTRAINT COMMENT_LIKE_CODE_PK PRIMARY KEY(COMM_LIKE_CODE);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_PK PRIMARY KEY(MEMBER_ID);
ALTER TABLE SUBSCRIBE ADD CONSTRAINT SUBS_CODE_PK PRIMARY KEY(SUBS_CODE);
ALTER TABLE VIDEO ADD CONSTRAINT VIDEO_CODE_PK PRIMARY KEY(VIDEO_CODE);
ALTER TABLE VIDEO_COMMNET ADD CONSTRAINT VIDEO_COMMNET_CODE_PK PRIMARY KEY(COMMNET_CODE);
ALTER TABLE VIDEO_LIKE ADD CONSTRAINT V_LIKE_CODE_PK PRIMARY KEY(V_LIKE_CODE);



